import type { Metadata } from "next";
import "@/app/globals.css";
import { Toaster } from "@/ui/_shared/sonner";



export const metadata: Metadata = {
  title: "Metreum",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`font-regular antialiased`}
      >
        {children}
        <Toaster/>
      </body>
    </html>
  );
}
